# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
"""Rewrite the imports of names that ``odoo.tools`` (or one of its modules)
does not provide anymore, from the data generated by
``tools/extract_tools_exports.py`` (``python_scripts/migrate_XXX_YYY/odoo_tools_imports.yaml``,
one rule per name, each with the Odoo commit that changed it).

    from odoo.tools import SQL, html_to_inner_content, ustr
        ->  from odoo.tools import SQL, ustr
            from odoo.tools.mail import html_to_inner_content
    from odoo.tools.query import Query  ->  from odoo.models import Query

* ``to: <module>``: the name is imported from that module instead (same
  definition, moved by the commit of the rule);
* ``import: from x import Y``: the name was a re-export of another library;
* ``to: null``: removed; the import is kept and reported as an error
  (file:line), unless a ``text_errors`` rule of the same step already
  reports it;
* ``tools.X`` / ``odoo.tools.X`` attribute accesses (after ``from odoo import
  tools``) of these names are reported, not rewritten.

Only absolute ``from ... import`` statements of the modules named by the rules
are touched: ``from odoo.tools.mail import X`` is left alone when ``X`` is still
there, so an already migrated file is unchanged (idempotent).
"""

import ast
import glob
import os
import re

import yaml

MAX_LINE = 100


def load_rules(path):
    """{(module, name): rule} of a data file."""
    with open(path, encoding="utf-8") as f:
        rules = yaml.safe_load(f) or []
    return {(rule["from"], rule["name"]): rule for rule in rules}


def load_error_patterns(step_dir):
    """Python ``text_errors`` patterns of a step (``migrate_XXX_YYY``)."""
    patterns = []
    for path in sorted(glob.glob(os.path.join(step_dir, "*.yaml"))):
        with open(path, encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
        patterns += list((data.get(".py") or {}).keys())
    return patterns


def _covered(name, text, patterns):
    """A text_errors rule already reports ``name`` in this file (one of its
    matches contains the name)."""
    word = re.compile(rf"(?<![A-Za-z0-9_]){re.escape(name)}(?![A-Za-z0-9_])")
    return any(
        word.search(match.group(0))
        for pattern in patterns if name in pattern
        for match in re.finditer(pattern, text)
    )


def _offsets(text):
    lines = text.splitlines(keepends=True)
    starts = [0, 0]
    for line in lines:
        starts.append(starts[-1] + len(line))

    def offset(lineno, col):
        return starts[lineno] + len(lines[lineno - 1].encode("utf-8")[:col].decode("utf-8", "replace"))

    return offset


def _alias(name, asname):
    return name + (f" as {asname}" if asname and asname != name else "")


def _statement(module, aliases, indent):
    line = f"from {module} import {', '.join(aliases)}"
    if len(indent) + len(line) <= MAX_LINE or len(aliases) == 1:
        return line
    inner = "".join(f"{indent}    {a},\n" for a in aliases)
    return f"from {module} import (\n{inner}{indent})"


def rewrite(text, rules, patterns=()):
    """Return (new text, reports): reports are (line, rule, kind) with kind
    "removed" (import kept), "attribute" (tools.X access) or "unchanged" (moved
    name whose import could not be rewritten safely)."""
    tree = ast.parse(text)
    modules = {module for module, _name in rules}
    offset = _offsets(text)
    edits, reports = [], []
    for node in ast.walk(tree):
        if not (isinstance(node, ast.ImportFrom) and node.level == 0 and node.module in modules):
            continue
        kept, moved = [], {}
        for alias in node.names:
            rule = rules.get((node.module, alias.name))
            if rule and rule.get("import"):
                origin = rule["import"].split()
                # "from x import Y" or "from x import Y as Z" (Z: the name in odoo.tools)
                moved.setdefault(origin[1], []).append(_alias(origin[3], alias.asname or alias.name))
            elif rule and rule.get("to"):
                moved.setdefault(rule["to"], []).append(_alias(alias.name, alias.asname))
            else:
                if rule and not _covered(alias.name, text, patterns):
                    reports.append((node.lineno, rule, "removed"))
                kept.append(_alias(alias.name, alias.asname))
        if not moved:
            continue
        start = offset(node.lineno, node.col_offset)
        end = offset(node.end_lineno, node.end_col_offset)
        indent = text[text.rfind("\n", 0, start) + 1:start]
        rest = text[end:text.find("\n", end) if "\n" in text[end:] else len(text)]
        if indent.strip() or rest.split("#")[0].strip():
            # "if x: from odoo.tools import y" / "...; other()": left as is, reported
            for alias in node.names:
                rule = rules.get((node.module, alias.name))
                if rule and (rule.get("to") or rule.get("import")):
                    reports.append((node.lineno, rule, "unchanged"))
            continue
        statements = [_statement(node.module, kept, indent)] if kept else []
        statements += [_statement(module, aliases, indent) for module, aliases in moved.items()]
        edits.append((start, end, f"\n{indent}".join(statements), node))
    # tools.X / odoo.tools.X with X not provided by odoo.tools anymore
    tools_names = {
        alias.asname or alias.name
        for node in tree.body if isinstance(node, ast.ImportFrom) and node.module == "odoo" and node.level == 0
        for alias in node.names if alias.name == "tools"
    }
    for node in ast.walk(tree):
        if not isinstance(node, ast.Attribute):
            continue
        value = node.value
        if (isinstance(value, ast.Name) and value.id in tools_names) or (
            isinstance(value, ast.Attribute) and value.attr == "tools"
            and isinstance(value.value, ast.Name) and value.value.id == "odoo"
        ):
            rule = rules.get(("odoo.tools", node.attr))
            if rule and not rule.get("deprecated") and not _covered(node.attr, text, patterns):
                reports.append((node.lineno, rule, "attribute"))
    for start, end, new, _node in sorted(edits, key=lambda e: e[0], reverse=True):
        text = text[:start] + new + text[end:]
    return text, reports


def _where(rule):
    if rule.get("import"):
        return rule["import"]
    if rule.get("to"):
        return f"from {rule['to']} import {rule['name']}"
    return None


def migrate(version, data_path, step_dir, **kwargs):
    """Global function body of python_scripts/migrate_XXX_YYY/odoo_tools_imports.py."""
    tools, logger = kwargs["tools"], kwargs["logger"]
    rules = load_rules(data_path)
    patterns = load_error_patterns(step_dir)
    markers = {module + " import" for module, _name in rules} | {"tools."}
    for path in tools.get_files(kwargs["module_path"], (".py",)):
        text = tools._read_content(path)
        if not any(marker in text for marker in markers):
            continue
        try:
            new, reports = rewrite(text, rules, patterns)
        except SyntaxError:
            continue
        if new != text:
            tools._write_content(path, new)
            logger.info("[%s] imports of names moved out of odoo.tools rewritten in %s" % (version, path))
        for line, rule, kind in reports:
            source = rule.get("proof") or "absent from the %s.0 sources" % version
            where = _where(rule)
            if kind == "attribute":
                message = "tools.%s does not exist anymore in odoo %s (%s)" % (rule["name"], version, source)
                message += ": %s" % where if where else ": it was removed"
            elif kind == "unchanged":
                message = "'%s' cannot be imported from %s anymore (%s): %s" % (
                    rule["name"], rule["from"], source, where)
            else:
                message = "'%s' cannot be imported from %s anymore: it was removed (%s)" % (
                    rule["name"], rule["from"], source)
                if rule.get("hint"):
                    message += "; a different %s exists in %s" % (rule["name"], rule["hint"])
            logger.error("[%s] %s. File %s:%s" % (version, message, path, line))
