# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
"""Names that cannot be imported from odoo.tools (or one of its modules) in 20.0.

Data: odoo_tools_imports.yaml next to this file, generated by
tools/extract_tools_exports.py (every rule carries the Odoo commit that
changed it). See odoo_module_migrate/odoo_tools_imports.py.
"""

import os

from odoo_module_migrate import odoo_tools_imports as _engine

_HERE = os.path.dirname(__file__)


def migrate_odoo_tools_imports(**kwargs):
    _engine.migrate(
        "20",
        os.path.join(_HERE, "odoo_tools_imports.yaml"),
        os.path.join(_HERE, "..", "..", "text_errors", "migrate_190_200"),
        **kwargs,
    )
