name: test

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"
      - "improve-migrator"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.13"]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          git config --global user.name "test"
          git config --global user.email "test@example.com"
          pip install -r test_requirements.txt
          pip install -e .
      - name: Run tests
        run: python -m pytest -q tests
